<div>
<p>
<span class="title">Uređivanje oglasa</span>
</p>
<div class="content2">
<form method="post" action="edit-ad?edit=<?php echo $this->ad->getId() ?>">
	<input type="hidden" name="id" value="<?php echo $this->ad->getId() ?>" />
    <span class="textContainer">
		<div class="msg" style="display:<?php echo $this->missingEntry ? "block" : "none" ?>">&nbsp;Niste unijeli sve obavezne unose&nbsp;</div>        
		<div class="msg" style="display:<?php echo $this->adUpdated ? "block" : "none" ?>">&nbsp;Promjene na oglasu su uspješno unesene.&nbsp;</div>
    </span><br />    
    <span class="textContainer">
    	<p>
        Ovdje možete urediti odabrani oglas.
        </p>
        <span <?php if(!$this->isOverdue){ echo "style='display:none'"; } ?>>
        Napomena: oglas je istekao, kako bi mogli uređivati oglas, prvo produžite njegovo trajanje<br /><br />
        <input type="submit" name="prolong" value="Produži trajanje oglasa za 14 dana" />
        </span>        
	</span>
    <ul style="padding-left:15px; padding-right:15px; margin-left:-5px">
        <li class="newAd" style="border-top:1px #103c9c dotted">
        	<p>
            <span>Status oglasa:</span>
            <span style="font-weight:bold"><?php echo $this->isOverdue ? "Istekao" : "Aktivan" ?></span>
            </p>
        </li>    
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Naslov oglasa:</span>
            </p>
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> style="width:800px" maxlength="50" type="text" name="title" value="<?php echo $this->ad->getTitle() ?>" />
        </li>
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Sadržaj oglasa:</span>
            </p>
            <textarea <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> id="taContent" name="taContent" style="width:800px; height:150px"><?php  echo str_replace(array('<br />', '<br/>', '<br>'), '', $this->ad->getText()) ?></textarea>
        </li>
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Trajanje oglasa (u danima):</span>
            </p>
            <select name="duration" disabled="disabled">
            	<option value="7" <?php if($this->ad->getDuration() == 7){ echo "selected='selected'"; } ?>>7</option>
                <option value="30" <?php if($this->ad->getDuration() == 30){ echo "selected='selected'"; } ?>>30</option>
                <option value="60" <?php if($this->ad->getDuration() == 60){ echo "selected='selected'"; } ?>>60</option>
                <option value="90" <?php if($this->ad->getDuration() == 90){ echo "selected='selected'"; } ?>>90</option>
                <option value="120" <?php if($this->ad->getDuration() == 120){ echo "selected='selected'"; } ?>>120</option>
            </select>
        </li>
        <li class="newAd">
        	<p style="margin-bottom:3px">
                <span>Županije u kojima vrijedi oglas:</span>
            </p>
            <p>
                <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> type="button" value="Odaberi sve županije" onclick="checkAllCounties()" />
            <p>
            <?php foreach($this->counties as $county): ?>
                <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array($county->getName(), $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch<?php echo($county->getId()) ?>" name="ch<?php echo($county->getId()) ?>" value="<?php echo($county->getId()) ?>" /><?php echo($county->getName()) ?><br />
            <?php endforeach ?>
        </li>
        <li class="newAd">
        	<p>
            <span>Izaberite kategoriju oglasa:</span>
            <select <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> name="adCategory">
            <?php foreach($this->category as $c): ?>
            	<option <?php if($this->ad->getCategoryName() == $c->getName()){ echo "selected='selected'"; } ?> value="<?php echo $this->escape($c->getId()) ?>"><?php echo $this->escape($c->getName()) ?></option>
            <?php endforeach ?>  
            </select>
            </p>
        </li>    
        <li style="list-style:none">
            <p style="visibility:<?php echo $this->isOverdue ? "hidden" : "visible" ?>">
	            <input type="submit" name="update" value="Predaj oglas" />
            </p>
        </li>   
    </ul>
</form>
</div>
</div>