<div>
<p>
<span class="title">Uređivanje oglasa</span>
</p>
<div class="content2">
<form method="post" action="edit-ad?edit=<?php echo $this->ad->getId() ?>">
	<input type="hidden" name="id" value="<?php echo $this->ad->getId() ?>" />
    <span class="textContainer">
		<div class="msg" style="display:<?php echo $this->missingEntry ? "block" : "none" ?>">&nbsp;Niste unijeli sve obavezne unose&nbsp;</div>        
		<div class="msg" style="display:<?php echo $this->adUpdated ? "block" : "none" ?>">&nbsp;Promjene na oglasu su uspješno unesene.&nbsp;</div>
    </span><br />    
    <span class="textContainer">
    	<p>
        Ovdje možete urediti odabrani oglas.
        </p>
        <span <?php if(!$this->isOverdue){ echo "style='display:none'"; } ?>>
        Napomena: oglas je istekao, kako bi mogli uređivati oglas, prvo produžite njegovo trajanje<br /><br />
        <input type="submit" name="prolong" value="Produži trajanje oglasa za 14 dana" />
        </span>        
	</span>
    <ul style="padding-left:15px; padding-right:15px; margin-left:-5px">
        <li class="newAd" style="border-top:1px #103c9c dotted">
        	<p>
            <span>Status oglasa:</span>
            <span style="font-weight:bold"><?php echo $this->isOverdue ? "Istekao" : "Aktivan" ?></span>
            </p>
        </li>    
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Naslov oglasa:</span>
            </p>
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> style="width:800px" maxlength="50" type="text" name="title" value="<?php echo $this->ad->getTitle() ?>" />
        </li>
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Sadržaj oglasa:</span>
            </p>
            <textarea <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> id="taContent" name="taContent" style="width:800px; height:150px"><?php  echo str_replace(array('<br />', '<br/>', '<br>'), '', $this->ad->getText()) ?></textarea>
        </li>
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Trajanje oglasa (u danima):</span>
            </p>
            <select name="duration" disabled="disabled">
            	<option value="7" <?php if($this->ad->getDuration() == 7){ echo "selected='selected'"; } ?>>7</option>
                <option value="30" <?php if($this->ad->getDuration() == 30){ echo "selected='selected'"; } ?>>30</option>
                <option value="60" <?php if($this->ad->getDuration() == 60){ echo "selected='selected'"; } ?>>60</option>
                <option value="90" <?php if($this->ad->getDuration() == 90){ echo "selected='selected'"; } ?>>90</option>
                <option value="120" <?php if($this->ad->getDuration() == 120){ echo "selected='selected'"; } ?>>120</option>
            </select>
        </li>
        <li class="newAd">
        	<p style="margin-bottom:3px">
            <span>Županije u kojima vrijedi oglas:</span>
            </p>
            <span style="border:1px #005BB7 solid; padding-top:3px; padding-right:5px">
    		<input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Cijela Hrvatska", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="chAll" name="chAll" onchange="if(this.checked){uncheckCounties()}" value="chAll" />Cijela Hrvatska
            </span><br />                             
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Grad Zagreb", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch1" name="ch1" value="1" onchange="if(this.checked){uncheckAllCountriesOption()}"/>Grad Zagreb<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Zagrebačka županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch2" name="ch2" value="2" onchange="if(this.checked){uncheckAllCountriesOption()}" />Zagrebačka županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Krapinsko-zagorska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch3" name="ch3" value="3" onchange="if(this.checked){uncheckAllCountriesOption()}" />Krapinsko-zagorska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Sisačko-moslavačka županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch4" name="ch4" value="4" onchange="if(this.checked){uncheckAllCountriesOption()}" />Sisačko-moslavačka županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Karlovačka županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch5" name="ch5" value="5" onchange="if(this.checked){uncheckAllCountriesOption()}" />Karlovačka županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Varaždinska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch6" name="ch6" value="6" onchange="if(this.checked){uncheckAllCountriesOption()}" />Varaždinska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Koprivničko-križevačka županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch7" name="ch7" value="7" onchange="if(this.checked){uncheckAllCountriesOption()}" />Koprivničko-križevačka županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Bjelovarsko-bilogorska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch8" name="ch8" value="8" onchange="if(this.checked){uncheckAllCountriesOption()}" />Bjelovarsko-bilogorska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Primorsko-goranska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch9" name="ch9" value="9" onchange="if(this.checked){uncheckAllCountriesOption()}" />Primorsko-goranska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Ličko-senjska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch10" name="ch10" value="10" onchange="if(this.checked){uncheckAllCountriesOption()}" />Ličko-senjska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Virovitičko-podravska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch11" name="ch11" value="11" onchange="if(this.checked){uncheckAllCountriesOption()}" />Virovitičko-podravska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Požeško-slavonska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch12" name="ch12" value="12" onchange="if(this.checked){uncheckAllCountriesOption()}" />Požeško-slavonska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Brodsko-posavska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch13" name="ch13" value="13" onchange="if(this.checked){uncheckAllCountriesOption()}" />Brodsko-posavska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Zadarska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch14" name="ch14" value="14" onchange="if(this.checked){uncheckAllCountriesOption()}" />Zadarska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Osječko-baranjska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch15" name="ch15" value="15" onchange="if(this.checked){uncheckAllCountriesOption()}" />Osječko-baranjska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Šibensko-kninska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch16" name="ch16" value="16" onchange="if(this.checked){uncheckAllCountriesOption()}" />Šibensko-kninska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Vukovarsko-srijemska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch17" name="ch17" value="17" onchange="if(this.checked){uncheckAllCountriesOption()}" />Vukovarsko-srijemska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Splitsko-dalmatinska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch18" name="ch18" value="18" onchange="if(this.checked){uncheckAllCountriesOption()}" />Splitsko-dalmatinska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Istarska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch19" name="ch19" value="19" onchange="if(this.checked){uncheckAllCountriesOption()}" />Istarska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Dubrovačko-neretvanska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch20" name="ch20" value="20" onchange="if(this.checked){uncheckAllCountriesOption()}" />Dubrovačko-neretvanska županija<br />
            <input <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> <?php if(in_array("Međimurska županija", $this->ad->getCountyArray())){ echo "checked='checked'"; } ?> type="checkbox" id="ch21" name="ch21" value="21" onchange="if(this.checked){uncheckAllCountriesOption()}" />Međimurska županija<br />
        </li>
        <li class="newAd">
        	<p>
            <span>Izaberite kategoriju oglasa:</span>
            <select <?php if($this->isOverdue){ echo "disabled='disabled'"; } ?> name="adCategory">
            <?php foreach($this->category as $c): ?>
            	<option <?php if($this->ad->getCategoryName() == $c->getName()){ echo "selected='selected'"; } ?> value="<?php echo $this->escape($c->getId()) ?>"><?php echo $this->escape($c->getName()) ?></option>
            <?php endforeach ?>  
            </select>
            </p>
        </li>    
        <li style="list-style:none">
            <p style="visibility:<?php echo $this->isOverdue ? "hidden" : "visible" ?>">
	            <input type="submit" name="update" value="Predaj oglas" />
            </p>
        </li>   
    </ul>
</form>
</div>
</div>