<div>
<p>
<span class="title">Registracija novog korisnika</span>
</p>
<div class="content2">
<form method="post" action="reg">
    <div class="textContainer">
		<div class="msg" style="display:<?php echo $this->passwordMismatch ? "block" : "none" ?>">&nbsp;Lozinka i ponovljena lozinka se ne poklapaju&nbsp;</div>
		<div class="msg" style="display:<?php echo $this->emailExists ? "block" : "none" ?>">&nbsp;E - mail adresa koju ste unijeli već postoji&nbsp;</div>
		<div class="msg" style="display:<?php echo $this->wrongUserName ? "block" : "none" ?>">&nbsp;Korisničko ime koje ste unijeli je već zauzeto&nbsp;</div>
		<div class="msg" style="display:<?php echo $this->missingEntry ? "block" : "none" ?>">&nbsp;Niste unijeli sve obavezne unose&nbsp;</div>
		<div class="msg" style="display:<?php echo $this->errorEmail ? "block" : "none" ?>">&nbsp;Greška kod slanja aktivacijskog e-maila, provjerite da li ste unijeli ispravnu adresu&nbsp;</div>
		<div class="msg" style="display:<?php echo $this->captchaError ? "block" : "none" ?>">Unijeli ste krivi tekst sa slike, pokušajte ponovno.</div>
        <div style="background-color:white; margin-bottom:5px; padding-left:10px; border:1px navy solid; line-height:25px; display:<?php echo $this->userInserted ? "block" : "none" ?>">&nbsp;Vaš korisnički račun je spreman, aktivirajte ga pomoću e-maila poslanog na adresu koju ste naveli prilikom registracije (moguće je da se poruka nalazi u "Junk" ili "Spam" direktoriju).<br />Aktivacijski e-mail trebali bi primiti unutar slijedećih 20 minuta ovisno o opterećenosti servera.<br />Hvala na registraciji!&nbsp;</div>
    </div><br />
    <div class="textContainer">
    	<p>
		Ovdje se možete besplatno registrirati. Polja označena crvenom zvjezdicom predstavljaju obavezne unose.
        </p>
    </div>
    
        <fieldset>
            <legend>Podaci za prijavu u sustav</legend>
                
            <ul style="padding-left:15px; padding-right:15px;">
                <li class="newAd">
                    <p style="margin-bottom:3px">
			<span><font style="color:red">* </font>Korisničko ime:</span>
                    </p>
                    <input style="width:400px" maxlength="20" type="text" name="username" value="<?php echo $this->escape($_SESSION["newUser"]->getUserName()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
			<span><font style="color:red">* </font>Lozinka:</span>
                    </p>
		    <input type="password" style="width:400px" maxlength="20" type="text" name="password1" value="<?php echo $this->escape($_SESSION["newUser"]->getPassword()) ?>" />
                </li>
                <li class="newAd" style="border:0px">
                    <p style="margin-bottom:3px">
			<span><font style="color:red">* </font>Ponovljena lozinka:</span>
                    </p>
                    <input type="password" style="width:400px" maxlength="20" type="text" name="password2" value="<?php echo $this->escape($_SESSION["newUser"]->getPassword()) ?>" />            
                </li>
        	</ul>
		</fieldset>
        
        <fieldset>
            <legend>Osobni podaci</legend>
            
            <ul style="padding-left:15px; padding-right:15px">
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Ime:</span>
                    </p>
                    <input style="width:400px" maxlength="20" type="text" name="name" value="<?php echo $this->escape($_SESSION["newUser"]->getName()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Prezime:</span>
                    </p>
                    <input style="width:400px" maxlength="20" type="text" name="lastName"  value="<?php echo $this->escape($_SESSION["newUser"]->getLastName()) ?>"/>
                </li>
           </ul>
        </fieldset>
        
        <fieldset>
            <legend>Kontakt podaci</legend>
                   
		    <ul style="padding-left:15px; padding-right:15px">
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Država:</span>
                    </p>
                    <input style="width:400px; background-color:transparent" readonly="readonly" maxlength="20" type="text" value="Hrvatska" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Županija:</span>
                    </p>
                    <select name="selCounty">
                        <option value="1" <?php if($_SESSION["newUser"]->getCountyId() == 1){ echo "selected='selected'"; } ?>>Grad Zagreb</option>
                        <option value="2" <?php if($_SESSION["newUser"]->getCountyId() == 2){ echo "selected='selected'"; } ?>>Zagrebačka županija</option>
                        <option value="3" <?php if($_SESSION["newUser"]->getCountyId() == 3){ echo "selected='selected'"; } ?>>Krapinsko-zagorska županija</option>
                        <option value="4" <?php if($_SESSION["newUser"]->getCountyId() == 4){ echo "selected='selected'"; } ?>>Sisačko-moslavačka županija</option>
                        <option value="5" <?php if($_SESSION["newUser"]->getCountyId() == 5){ echo "selected='selected'"; } ?>>Karlovačka županija</option>
                        <option value="6" <?php if($_SESSION["newUser"]->getCountyId() == 6){ echo "selected='selected'"; } ?>>Varaždinska županija</option>
                        <option value="7" <?php if($_SESSION["newUser"]->getCountyId() == 7){ echo "selected='selected'"; } ?>>Koprivničko-križevačka županija</option>
                        <option value="8" <?php if($_SESSION["newUser"]->getCountyId() == 8){ echo "selected='selected'"; } ?>>Bjelovarsko-bilogorska županija</option>
                        <option value="9" <?php if($_SESSION["newUser"]->getCountyId() == 9){ echo "selected='selected'"; } ?>>Primorsko-goranska županija</option>
                        <option value="10" <?php if($_SESSION["newUser"]->getCountyId() == 10){ echo "selected='selected'"; } ?>>Ličko-senjska županija</option>
                        <option value="11" <?php if($_SESSION["newUser"]->getCountyId() == 11){ echo "selected='selected'"; } ?>>Virovitičko-podravska županija</option>
                        <option value="12" <?php if($_SESSION["newUser"]->getCountyId() == 12){ echo "selected='selected'"; } ?>>Požeško-slavonska županija</option>
                        <option value="13" <?php if($_SESSION["newUser"]->getCountyId() == 13){ echo "selected='selected'"; } ?>>Brodsko-posavska županija</option>
                        <option value="14" <?php if($_SESSION["newUser"]->getCountyId() == 14){ echo "selected='selected'"; } ?>>Zadarska županija</option>
                        <option value="15" <?php if($_SESSION["newUser"]->getCountyId() == 15){ echo "selected='selected'"; } ?>>Osječko-baranjska županija</option>
                        <option value="16" <?php if($_SESSION["newUser"]->getCountyId() == 16){ echo "selected='selected'"; } ?>>Šibensko-kninska županija</option>
                        <option value="17" <?php if($_SESSION["newUser"]->getCountyId() == 17){ echo "selected='selected'"; } ?>>Vukovarsko-srijemska županija</option>
                        <option value="18" <?php if($_SESSION["newUser"]->getCountyId() == 18){ echo "selected='selected'"; } ?>>Splitsko-dalmatinska županija</option>
                        <option value="19" <?php if($_SESSION["newUser"]->getCountyId() == 19){ echo "selected='selected'"; } ?>>Istarska županija</option>
                        <option value="20" <?php if($_SESSION["newUser"]->getCountyId() == 20){ echo "selected='selected'"; } ?>>Dubrovačko-neretvanska županija</option>
                        <option value="21" <?php if($_SESSION["newUser"]->getCountyId() == 21){ echo "selected='selected'"; } ?>>Međimurska županija</option>                              
                    </select>
                 </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Grad:</span>
                    </p>
                    <input style="width:400px" maxlength="50" type="text" name="city" value="<?php echo $this->escape($_SESSION["newUser"]->getCity()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Poštanski broj:</span>
                    </p>
                    <input style="width:400px" maxlength="20" type="text" name="postalCode" value="<?php echo $this->escape($_SESSION["newUser"]->getPostalCode()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Ime ulice:</span>
                    </p>
                    <input style="width:400px" maxlength="50" type="text" name="streetName" value="<?php echo $this->escape($_SESSION["newUser"]->getStreetName()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Kućni broj:</span>
                    </p>
                    <input style="width:400px" maxlength="50" type="text" name="streetNumber" value="<?php echo $this->escape($_SESSION["newUser"]->getStreetNumber()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <font style="color:red">* </font><span>Telefon 1:</span>
                    </p>
                    <input style="width:400px" maxlength="50" type="text" name="telephone1" value="<?php echo $this->escape($_SESSION["newUser"]->getTelephone1()) ?>" />
                </li>
                <li class="newAd">
                    <p style="margin-bottom:3px">
                    <span>Telefon 2:</span>
                    </p>
                    <input style="width:400px" maxlength="50" type="text" name="telephone2" value="<?php echo $this->escape($_SESSION["newUser"]->getTelephone2()) ?>" />
                </li>
                <li class="newAd" style="border:0px">
                    <p style="margin-bottom:3px">
                    <span><font style="color:red">* </font>E - mail (Vašu e-mail adresu nećemo koristiti u reklamne, komercijalne ili bilo koje druge svrhe osim registracije):</span>
                    </p>
                    <input style="width:400px" maxlength="50" type="text" name="email" value="<?php echo $this->escape($_SESSION["newUser"]->getEmail()) ?>" />
                </li>
                <li class="newAd" style="border:0px">
                    <strong>Sigurnosna provjera</strong><br />
                    Unesite tekst sa donje slike: <input type="text" name="captcha[input]" maxlength="20" /> 
                </li>                
                <li class="newAd" style="border:0px">
                	<?php echo $this->captchaImage ?>
                </li>
           </ul>
    </fieldset>
<input type="hidden" name="captcha[id]" value="<?php echo $this->escape($this->captchaMD5) ?>" />
<p style="margin-left:15px">
    <input type="submit" value="Registriraj" />
</p>
</form>    
</div>
</div>
