<div>
<p>
<span class="title">Registracija</span>
</p>
<div class="content2">
    <span class="textContainer">
		<div style="background-color:white; margin-bottom:5px; border:1px navy solid; height:30px; line-height:30px">&nbsp;<?php echo $this->confirmed ? "Čestitamo, Vaš korisnički račun je uspješno aktiviran. <a style='text-decoration:underline; font-weight:bold' href='login'>Ovdje</a> se možete prijaviti u sustav." : "Aktivacija Vašeg korisničkog računa nije uspjela. U slučaju tehničkih problema javite se administratoru." ?>&nbsp;</div>
	</span>
</div>
</div>