<div>
<p>
<span class="title">Predaja oglasa</span>
</p>
<div class="content2">
<form method="post" action="new-ad">
    <span class="textContainer">
        <div class="msg" style="display:<?php echo $this->missingEntry ? "block" : "none" ?>">&nbsp;Niste ispunili sva obavezna polja!&nbsp;</div>    
    	<div class="msg" style="display:<?php echo $this->adInserted ? "block" : "none" ?>">&nbsp;Oglas je uspješno predan!&nbsp;</div>   
    </span><br />
    <span class="textContainer">
    	<p>
        Ovdje možete predati Vaš novi oglas. Polja označena crvenom zvjezdicom predstavljaju obavezne unose.
        </p>
	</span>

        <ul style="padding-left:15px; padding-right:15px; margin-left:-5px">
            <li class="newAd" style="border-top:1px #103c9c dotted">
                <p style="margin-bottom:3px">
                <span><font style="color:red">* </font>Naslov oglasa:</span>
                </p>
                <input style="width:800px" maxlength="50" type="text" name="title" value="<?php echo $_SESSION["newAd"]->getTitle() ?>" />
            </li>
            <li class="newAd">
                <p style="margin-bottom:3px">
                <span><font style="color:red">* </font>Sadržaj oglasa:</span>
                </p>
                <textarea id="taContent" name="taContent" style="width:800px; height:150px"><?php echo $_SESSION["newAd"]->getText() ?></textarea>
            </li>
            <li class="newAd">
                <p style="margin-bottom:3px">
                <span>Trajanje oglasa (u danima):</span>
                </p>
                <select name="duration">
                    <option value="7">7</option>
                    <option value="30">30</option>
                    <option value="60">60</option>
                    <option value="90">90</option>
                    <option value="120">120</option>
                </select>
            </li>
            <li class="newAd">
                <p>
                    <span>Županije u kojima vrijedi oglas:</span>
                </p>
                <p>
                    <input type="button" value="Odaberi sve županije" onclick="checkAllCounties()" />
                <p>
                <?php foreach($this->counties as $county): ?>
                    <input type="checkbox" id="ch<?php echo($county->getId()) ?>" name="ch<?php echo($county->getId()) ?>" value="<?php echo($county->getId()) ?>" /><?php echo($county->getName()) ?><br />
                <?php endforeach ?>
            </li>
            <li class="newAd">
                <p>
                <span>Izaberite kategoriju oglasa:</span>
                <select name="adCategory">
                <?php foreach($this->category as $c): ?>
                    <option value="<?php echo $this->escape($c->getId()) ?>"><?php echo $this->escape($c->getName()) ?></option>
                <?php endforeach ?>  
                </select>
                </p>
            </li>
        </ul>

<p style="margin-left:15px">
    <input type="submit" value="Predaj oglas" />
</p>
</form>    
</div>
</div>